eureka:
  client:
    serviceUrl:
      # 服务注册地址
      defaultZone: http://localhost:8888/eureka/

server:
  # 运行端口
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    # 服务注册名称
    name: service-yns-portal

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names: ''
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

  #redis
  redis:
    host: 152.136.247.100
    port: 6379
    password: # 如果有密码
    timeout: 2000
    session:
      store-type: redis
      redis:
        namespace: spring:session
